### PR TITLE
Fix detection of episodes list for Neko-Sama

### PR DESCRIPTION
**Pull request by louisroyer**
This website updated the way they display episode list.

### CODE REVIEW

**Comment by louisroyer** [comment]
Tests don't fail on my machine, maybe it is because of CI cache?
```
  Anime Cat
    https://animecat.net/anime/episode/19080-tomo-chan-wa-onnanoko-07_vostfr
      Cached
      Passed
    https://animecat.net/anime/episode/3458-hagane-no-renkinjutsushi-fullmetal-alchemist-03_vostfr
      Cached
      Passed
    https://animecat.net/anime/episode/3458-hagane-no-renkinjutsushi-fullmetal-alchemist-03_vf
      Cached
      Passed
    https://animecat.net/anime/info/3458-hagane-no-renkinjutsushi-fullmetal-alchemist_vostfr
      Cached
      Passed
    https://animecat.net/anime/info/3458-hagane-no-renkinjutsushi-fullmetal-alchemist_vf
      Passed
    https://animecat.net/anime/info/19050-4-nin-wa-sorezore-uso-wo-tsuku_vostfr
      Passed
 ```

**Review by lolamtisch — CHANGES_REQUESTED** [review]
I updated the caches, but it seems like the page changed again.

Can you add both domains in the pageInteface too? you can just use an array

**Comment by louisroyer** [comment]
how can i clear the cache on my machine?

**Comment by lolamtisch** [comment]
> how can i clear the cache on my machine?

Delete everything inside `test/dist`

**Comment by louisroyer** [comment]
it's now ok on my side but the website now timeouts from the CI.

**Pull request merged**
