### PR TITLE
Update shikimori domain name

### PR DESCRIPTION
**Pull request by matryosha**
From .one to .me domain as one has been temp(?) lost

Source: https://shikimori.me/forum/news/505429-novyy-domen-sayta-shikimori-me Important part from there is:
  `В любом случае новый домен сайта теперь shikimori.me. Даже когда/если
  я верну старый домен, то основным доменом сайта останется новый, чтобы
  не устраивать еще один переезд.`
Which roughly translates as shikimori.me would the main domain even after restoring old ones.

### CODE REVIEW

**Comment by matryosha** [comment]
@lolamtisch

**Comment by lolamtisch** [comment]
We just had a release. Next release will be in a few weeks. I did not forget. 😉

**Comment by matryosha** [comment]
From https://shikimori.me/forum/news/506738-novyy-domen-sayta-shikimori-me-v2

> [...]Обращения к апи [shikimori.one](https://shikimori.one/) будут работают без редиректа, чтобы не ломались приложения, использующие апи сайта. 

So the meaning that old domain redirects to new one so api access through .one works.

Either close it as it now works anyway or change the domain to main one in case something happens as it was last time.

**Comment by lolamtisch** [comment]
Good to know. Yeah keep the PR open it makes sense to migrate to the new domain either way.

**Pull request merged**
