### PR TITLE
added isekaiscan pages

### PR DESCRIPTION
**Pull request by zamounet**
Added Isekaiscan domain.

Straight copy from #757 and #857.

### CODE REVIEW

**Review by lolamtisch — CHANGES_REQUESTED** [review]
The onsite UI has to be fixed
image

**Comment by zamounet** [comment]
The UI should be fixed now.

Took a while, did not get a notification on this..

**Review by lolamtisch — CHANGES_REQUESTED** [review]
Nothing changed, sure you did push the changes correctly?

**Comment by lolamtisch** [comment]
Sorry I did not noticed the force push breaking the branch localy. It looks better now but the chapters and volumes are still broken.



image

**Pull request merged**
