### PR TITLE
fix netflix

### PR DESCRIPTION
**Pull request by henrik9999**

### CODE REVIEW

**Comment by officialpiyush** [comment]
any ETA when this'd be checked and/or merged?

**Comment by henrik9999** [comment]
> any ETA when this'd be checked and/or merged?

There are no ETA it will be merged before the next release and for that release is no ETA

**Comment by officialpiyush** [comment]
oh, shouldn't bug fixes be shipped faster? 👀

**Comment by lolamtisch** [comment]
Unfortunatly we cant, as updates always make problems for the users. Like auto disabling exentions for example. So Releases are normaly around once a month. Next release is probably in around 2 weeks.

**Comment by officialpiyush** [comment]
> Unfortunatly we cant, as updates always make problems for the users. Like auto disabling exentions for example. So Releases are normaly around once a month. Next release is probably in around 2 weeks.

makes sense. What do you think of maintaining a development branch, which can be updated on the go, but merged into stable main and published to extension's, when it's time to publish. This way, users may be able to load unpacked extension, those who want a bug fix soon-er? It kind of feels lost to not have Mal-Sync track lol

**Comment by henrik9999** [comment]
> > Unfortunatly we cant, as updates always make problems for the users. Like auto disabling exentions for example. So Releases are normaly around once a month. Next release is probably in around 2 weeks.
> 
> makes sense. What do you think of maintaining a development branch, which can be updated on the go, but merged into stable main and published to extension's, when it's time to publish. This way, users may be able to load unpacked extension, those who want a bug fix soon-er? It kind of feels lost to not have Mal-Sync track lol

Most people don't understand development branches and then always create prs for the master branch

**Comment by officialpiyush** [comment]
rip, still a pain tho, can't auto track episodes. Hope you figure out something soon :p

**Comment by officialpiyush** [comment]
beep boop, still waiting for a fix :p

**Comment by lolamtisch** [comment]
Next release is probably in 1-2 weeks, as we have a lot in the pipeline currently.

**Review by lolamtisch — APPROVED** [review]

**Pull request merged**
