### PR TITLE
Add HinataSoul

### PR DESCRIPTION
**Pull request by uKaigo**
I couldn't run the tests, since it was taking way too long and it looked like it was frozen. But everything should work.

`paginationNext` wasn't running because `elementEp` was broken, but that should be fixed.

I'm testing for episode 37, but I'm not sure if pagination works in testing, will remove if it doesn't.

### CODE REVIEW

**Comment by uKaigo** [comment]
I don't know why page tests are failing. It works when running the extension.

**Comment by lolamtisch** [comment]
Is normal

**Comment by Source-Dom** [comment]
Btw your `pages.ts` is missing a semicolon `;` on your 135th line.

**Review by lolamtisch — CHANGES_REQUESTED** [review]
Fix the missing ;

**Pull request merged**
