### PR TITLE
[TASK] Chnage animesuge TLD from .io to .to

### PR DESCRIPTION
**Pull request by amitojsingh366**
The owner of animesuge has switched domains from [animesuge.io](https://animesuge.io) to [animesuge.to](https://animesuge.to), and this made MALSync stop working.
These changes should fix the above mentioned issue

### CODE REVIEW

**Comment by henrik9999** [comment]
its already fixed for the next release

**Comment by amitojsingh366** [comment]
oh ok, when is it getting released?

**Comment by henrik9999** [comment]
there are no eta

but you can use a workaround in malsync for now

You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.

```animesuge``` -> ```https://animesuge.to/```

or you could just use 9anime since animesuge is just using 9anime

**Comment by amitojsingh366** [comment]
> there are no eta
> 
> but you can use a workaround in malsync for now
> 
> You will need to add the custom domain like below. There is a button Custom Domains in the settings. You possibly need to restart the browser afterwards.
> 
> `animesuge` -> `https://animesuge.to/`
> 
> or you could just use 9anime since animesuge is just using 9anime

thanks for your help, it worked!

**Pull request closed without merging**
